CREATE DATABASE IF NOT EXISTS wp_db;
CREATE USER 'ichouare'@'%' IDENTIFIED BY '1998';
CREATE USER 'issam'@'%' IDENTIFIED BY '1111';
GRANT ALL PRIVILEGES ON wp_db.* TO ichouare@'%' IDENTIFIED BY '1998';
FLUSH PRIVILEGES;
