CREATE DATABASE IF NOT EXISTS  $db_name;
CREATE USER 'ichouare'@'%' IDENTIFIED BY '1998';
CREATE USER '$db1_user'@'%' IDENTIFIED BY '$db1_pwd';
GRANT ALL PRIVILEGES ON WORDPRESSDB.* TO 'ichouare'@'%' IDENTIFIED BY '1998';
FLUSH PRIVILEGES
